name: Deploy naar Server via ftp 🚀

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Production via FTP
    runs-on: ubuntu-latest
    environment: productie
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 📤 Deploy to Production Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_UNAME_PROD }}
          password: ${{ secrets.FTP_PASS_PROD }}
          protocol: ftps
          server-dir: /ftp

  deploy-test:
    if: github.ref == 'refs/heads/test'
    name: Deploy to Test Server via FTP
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 📤 Deploy to Test Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_UNAME_TEST }}
          password: ${{ secrets.FTP_PASS_TEST }}
          protocol: ftps
          server-dir: /
